name: CI

on: [push]

jobs:
  testing:
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.cache/yarn
          key: ${{ matrix.os }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ matrix.os }}-

      - name: Install deps
        run: yarn install

      - name: Install SSH server
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          mkdir -p "$HOME/.ssh"
          chmod 0700 "$HOME/.ssh"
          ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
          cat "$HOME/.ssh/id_rsa.pub" >> "$HOME/.ssh/authorized_keys"
          chmod 640 "$HOME/.ssh/authorized_keys"
          echo "NoHostAuthenticationForLocalhost yes" >> ~/.ssh/config
          sudo systemctl restart ssh
          ssh localhost "uname"
          whoami

      - name: Building
        run: |
          yarn build

      - name: Testing rowen
        run: |
          cd pkgs/testings
          yarn test

  # build-lint:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest]
  #       node-version: [15.x]
  #       steps: [build, lint]

  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup Node.js for use with actions
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Cache
  #       uses: actions/cache@v1.0.0
  #       with:
  #         path: ~/.cache/yarn
  #         key: ${{ matrix.os }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
  #         restore-keys: |
  #           ${{ matrix.os }}-

  #     - name: Install deps
  #       run: yarn install

  #     - name: Build package
  #       if: ${{ matrix.steps == 'build' }}
  #       run: |
  #         cd pkgs/lys
  #         yarn prepublishOnly

  #     - name: Linting @fleur/lys
  #       if: ${{ matrix.steps == 'lint' }}
  #       run: |
  #         cd pkgs/lys
  #         yarn eslint ./src
